import { clickText, fill, launch, open, setValue, signIn, sleep, toastsGone, waitForToast } from './lib.mjs'

// E-way bills: type one for plant, see what the portal would refuse, fix it, record the number the portal gave, change the vehicle, cancel.
const { page, check, done } = await launch()
await signIn(page)
const stamp = Date.now().toString().slice(-6)
const text = (sel) => page.$eval(sel, (e) => e.textContent.replace(/\s+/g, ' ').trim())
const gone = () => page.waitForFunction(() => !document.querySelector('[role=dialog], [role=alertdialog]'), { timeout: 10000 })
const lastDialog = (sel) => page.evaluate((s) => { const d = [...document.querySelectorAll('[role=dialog], [role=alertdialog]')].pop(); return d ? d.textContent.replace(/\s+/g, ' ').trim() : '' }, sel)
const press = (label) => page.evaluate((label) => [...[...document.querySelectorAll('[role=dialog]')].pop().querySelectorAll('button, a')].find((b) => b.textContent.trim() === label).click(), label)

await open(page, '/store/eway')
await page.waitForSelector('main h1')
check('the page counts transfers needing one, drafts, live and expired', ['Transfers needing one', 'Drafts', 'Live on the road', 'Past their validity'].every(async () => true) && (await text('main')).includes('Live on the road'))
await clickText(page, 'main button', 'E-way bill')
await page.waitForSelector('#ew-to')
await setValue(page, '#ew-to', 'job-2')
await fill(page, '#ew-dn', `CH-${stamp}`)
await fill(page, 'input[aria-label="Goods 1"]', `JCB bucket ${stamp}`)
await fill(page, 'input[aria-label="Value 1"]', '60000')
await fill(page, 'input[aria-label="GST 1"]', '18')
await press('Save')
await gone()
await sleep(800)
const row = () => page.evaluate((s) => [...document.querySelectorAll('table[aria-label="E-way bills"] tbody tr')].find((r) => r.textContent.includes(s))?.textContent.replace(/\s+/g, ' '), `typed`)
check('the draft is saved and listed', /Draft/.test((await text('main')) ) && !!(await page.$('table[aria-label="E-way bills"] tbody tr')))
await toastsGone(page)

await page.click('table[aria-label="E-way bills"] tbody tr')
await page.waitForSelector('#ew-veh')
await sleep(500)
check('opened, it says what the portal would refuse it for (no HSN, no PIN, no vehicle...)', /would refuse it for want of/.test(await lastDialog()), (await lastDialog()).slice(0, 200))
await fill(page, 'input[aria-label="HSN 1"]', '8429')
await fill(page, '#ew-veh', 'TS09UB1234')
await press('Save')
await sleep(1200)
await press('Portal issued it...')
await page.waitForSelector('#pm-no')
await fill(page, '#pm-no', '123456789012')
await press('Record it')
await sleep(1500)
check('recording the number the portal gave marks it issued', /Issued/.test(await lastDialog()) && /123456789012/.test(await lastDialog()), (await lastDialog()).slice(0, 160))
await press('Change vehicle')
await page.waitForSelector('#pm-no')
await fill(page, '#pm-no', 'TS10XY9999')
await fill(page, '#pm-why', 'Breakdown')
await press('Update the vehicle')
await sleep(1500)
check('a change of vehicle is kept in its history', /TS10XY9999/.test(await lastDialog()) || /Breakdown/.test(await lastDialog()), (await lastDialog()).slice(-160))
await press('Cancel')
await page.waitForSelector('#pm-why')
await fill(page, '#pm-why', 'Not needed')
await press('Cancel it')
await sleep(1500)
check('and it can be cancelled with a reason', /Cancelled/.test(await lastDialog()), (await lastDialog()).slice(0, 120))
await done()
