import { clickText, fill, launch, open, setValue, signIn, sleep, toastsGone, waitForToast } from './lib.mjs'

// Quality: walk a checklist and fail it, raise the non-conformance from it and close that; log cubes, read them below grade.
const { page, check, done } = await launch()
await signIn(page)
const stamp = Date.now().toString().slice(-6)
const text = (sel) => page.$eval(sel, (e) => e.textContent.replace(/\s+/g, ' ').trim())
const gone = () => page.waitForFunction(() => !document.querySelector('[role=dialog]'), { timeout: 10000 })

await open(page, '/projects/quality')
await page.waitForFunction(() => document.querySelector('#qc-job option[value]'), { timeout: 10000 })
await setValue(page, '#qc-job', await page.$eval('#qc-job option[value]:not([value=""])', (o) => o.value))
await sleep(600)
await clickText(page, 'main button', 'New')
await page.waitForSelector('#qn-where')
await fill(page, '#qn-where', `Raft ${stamp}`)
await page.waitForFunction(() => document.querySelector('#qn-list')?.options.length > 0)
await clickText(page, '[role=dialog] button', 'Start it')
await page.waitForSelector('table[aria-label=Checks]')
const rows = await page.$$eval('table[aria-label=Checks] tbody tr', (r) => r.length)
check('the checklist opens with its checks to walk', rows > 2, rows + ' checks')
await page.evaluate(() => {
  const trs = [...document.querySelectorAll('table[aria-label=Checks] tbody tr')]
  trs.forEach((tr, i) => tr.querySelectorAll('input[type=radio]')[i === 0 ? 1 : 0].click())
})
await fill(page, 'table[aria-label=Checks] tbody tr:first-child input[type=text], table[aria-label=Checks] tbody tr:first-child input:not([type])', 'Cover is short')
await clickText(page, '[role=dialog] button', 'Close it')
await waitForToast(page, 'failed')
await gone()
await sleep(500)
const irow = () => page.evaluate((s) => [...document.querySelectorAll('table[aria-label=Inspections] tbody tr')].find((r) => r.textContent.includes(s))?.textContent.replace(/\s+/g, ' '), stamp)
check('one check not ok fails the inspection', /Failed/.test(await irow()) && /1 not ok/.test(await irow()), await irow())
await toastsGone(page)

// Raise the NCR from the failed inspection
await page.evaluate((s) => [...document.querySelectorAll('table[aria-label=Inspections] tbody tr')].find((r) => r.textContent.includes(s)).querySelector('button').click(), stamp)
await page.waitForSelector('table[aria-label=Checks]')
await clickText(page, '[role=dialog] button', 'Raise NCR')
await page.waitForSelector('#nc-who')
await fill(page, '#nc-who', `Shuttering gang ${stamp}`)
await clickText(page, '[role=dialog] button', 'Raise it')
await waitForToast(page, 'raised')
await sleep(800)
check('the NCR is raised, filled in from what failed, and the page moves to it', (await text('table[aria-label="Non-conformances"] tbody')).includes(`Shuttering gang ${stamp}`), (await text('table[aria-label="Non-conformances"] tbody')).slice(0, 160))
await toastsGone(page)
await page.evaluate((s) => [...document.querySelectorAll('table[aria-label="Non-conformances"] tbody tr')].find((r) => r.textContent.includes(s)).querySelector('button').click(), stamp)
await page.waitForSelector('#pm-note')
await fill(page, '#pm-note', 'Cover corrected and re-checked')
await clickText(page, '[role=dialog] button', 'Close it')
await waitForToast(page, 'closed')
await gone()
await sleep(500)
check('closing the NCR records what was done', (await text('table[aria-label="Non-conformances"] tbody')).includes('Cover corrected'))
await toastsGone(page)

// Cubes
await clickText(page, '[role=tab]', 'Cube tests')
await clickText(page, 'main button', 'New')
await page.waitForSelector('#cs-where')
await fill(page, '#cs-where', `Raft pour ${stamp}`)
await clickText(page, '[role=dialog] button', 'Log the set')
await waitForToast(page, 'logged')
await gone()
await sleep(500)
const crow = () => page.evaluate((s) => [...document.querySelectorAll('table[aria-label="Cube sets"] tbody tr')].find((r) => r.textContent.includes(s))?.textContent.replace(/\s+/g, ' '), stamp)
check('the set is logged with its tests coming due', /due/.test(await crow()), await crow())
await toastsGone(page)
await page.evaluate((s) => [...document.querySelectorAll('table[aria-label="Cube sets"] tbody tr')].find((r) => r.textContent.includes(s)).querySelector('button').click(), stamp)
await page.waitForSelector('#cr-str')
await setValue(page, '#cr-age', '28')
await fill(page, '#cr-str', '17.5, 18, 18.5')
await clickText(page, '[role=dialog] button', 'Record it')
await waitForToast(page, 'N/mm2')
await gone()
await sleep(500)
check('a 28-day result well under M25 is below grade, with a way to raise an NCR', /below grade/.test(await crow()) && /Raise NCR/.test(await crow()), await crow())
await done()
