import { clickText, fill, launch, open, setValue, signIn, sleep, toastsGone, waitForToast } from './lib.mjs'

// Equipment: add a machine, deploy it to a site, log a day (the cost lands on the site), service it out of action and bring it back.
const { page, check, done } = await launch()
await signIn(page)
const stamp = Date.now().toString().slice(-6)
const name = `QA Roller ${stamp}`
const text = (sel) => page.$eval(sel, (e) => e.textContent.replace(/\s+/g, ' ').trim())
const gone = () => page.waitForFunction(() => !document.querySelector('[role=dialog]'), { timeout: 10000 })
const row = () => page.evaluate((n) => [...document.querySelectorAll('table[aria-label=Machines] tbody tr')].find((r) => r.textContent.includes(n))?.textContent.replace(/\s+/g, ' '), name)
const press = (label) => page.evaluate((n, label) => [...[...document.querySelectorAll('table[aria-label=Machines] tbody tr')].find((r) => r.textContent.includes(n)).querySelectorAll('button')].find((b) => b.textContent.trim() === label).click(), name, label)

await open(page, '/projects/equipment')
await page.waitForSelector('main h1')
await clickText(page, 'main button', 'Machine')
await page.waitForSelector('#mc-name')
await fill(page, '#mc-name', name)
await fill(page, '#mc-reg', `TS09QA${stamp.slice(-4)}`)
await fill(page, '#mc-every', '250')
await clickText(page, '[role=dialog] button', 'Save the machine')
await waitForToast(page, 'saved')
await gone()
await sleep(600)
check('the machine is on the register, in the yard', /EQP-/.test(await row()) && /Yard/.test(await row()) && /Available/.test(await row()), await row())
await toastsGone(page)

await press('Deploy')
await page.waitForSelector('#mv-to')
await setValue(page, '#mv-to', await page.$eval('#mv-to option[value]:not([value=""])', (o) => o.value))
await clickText(page, '[role=dialog] button', 'Deploy it')
await waitForToast(page, name.split(' ')[0] === 'QA' ? 'EQP' : 'EQP')
await gone()
await sleep(600)
check('deployed, it shows its site and offers Log day', /Deployed/.test(await row()) && !/Yard/.test(await row()))
await toastsGone(page)

await press('Log day')
await page.waitForSelector('#lg-hours')
await fill(page, '#lg-hours', '6')
await fill(page, '#lg-litres', '20')
await fill(page, '#lg-rate', '90')
await fill(page, '#lg-op', 'Raju')
await clickText(page, '[role=dialog] button', 'Log the day')
await waitForToast(page, 'Cost')
await gone()
await sleep(700)
check('a logged day costs the diesel: 20 L at 90 is 1,800', /1,800/.test(await row()), await row())
await toastsGone(page)

await clickText(page, 'table[aria-label=Machines] tbody button', name)
await page.waitForSelector('table[aria-label="Daily log"] tbody tr')
check('its history shows the day, who ran it and the diesel', /Raju/.test(await text('table[aria-label="Daily log"]')) && /20/.test(await text('table[aria-label="Daily log"]')))

await press('Service')
await page.waitForSelector('#sv-desc')
await setValue(page, '#sv-kind', 'Breakdown')
await fill(page, '#sv-desc', 'Hydraulic hose burst')
await fill(page, '#sv-parts', '4000')
await page.evaluate(() => document.querySelector('[role=dialog] input[type=checkbox]').click())
await clickText(page, '[role=dialog] button', 'Record it')
await sleep(1500)
await gone()
check('a breakdown that keeps it out of service puts it under repair', /Under repair/.test(await row()), await row())
await press('Back at work')
await sleep(1200)
check('and Back at work returns it to the yard', /Available|Deployed/.test(await row()) && !/Under repair/.test(await row()), await row())
await done()
