import { clickCell, clickText, fill, launch, open, signIn, sleep, toastsGone, waitForToast } from './lib.mjs'

// Clients > Tenders & Estimates: open a tender, price an item by its rate build-up, submit it, win it, get the work order.
const { page, check, done } = await launch()
await signIn(page)
await open(page, '/clients/estimates')
await page.waitForSelector('table[aria-label=Estimates]')
const stamp = Date.now().toString().slice(-6)
const title = `E2E Drain ${stamp}`
const main = () => page.$eval('main', (e) => e.textContent.replace(/\s+/g, ' '))
const dialog = () => page.$eval('[role=dialog]', (e) => e.textContent.replace(/\s+/g, ' '))

check('the list loads with its figures', (await main()).includes('Strike rate'))
await clickText(page, 'button', 'New estimate')
await page.waitForSelector('#es-title')
await fill(page, '#es-title', title)
await fill(page, '#es-client', 'HMWSSB')
await clickText(page, 'button', 'Open it')
await page.waitForFunction((t) => location.pathname.includes('/estimates/') && document.querySelector('main h1')?.textContent.includes(t), {}, title)
check('a new estimate opens at once with overhead 10% and profit 8%', (await page.$eval('#es-oh', (e) => e.value)) === '10' && (await page.$eval('#es-pf', (e) => e.value)) === '8')
await toastsGone(page)

await fill(page, '#ei-no', '1')
await fill(page, '#ei-desc', 'M20 concrete to drain')
await fill(page, '#ei-uom', 'Cum')
await fill(page, '#ei-qty', '10')
await fill(page, '#ei-rate', '100')
await clickText(page, 'button', 'Add')
await page.waitForFunction(() => document.querySelector('table[aria-label="Estimate items"]')?.textContent.includes('M20 concrete'), { timeout: 8000 })
check('an item added with a typed cost rate is priced with overhead and profit on top (100 -> 118.80)', (await main()).includes('118.80'), (await main()).slice(0, 200))

await clickText(page, 'table[aria-label="Estimate items"] button', 'Rate')
await page.waitForSelector('[role=dialog] [role=grid]')
await clickCell(page, 0, 0, 1, '[role=dialog]')
await page.keyboard.type('Cement OPC 53'); await page.keyboard.press('Tab')
await page.keyboard.type('bag'); await page.keyboard.press('Tab')
await page.keyboard.type('0.5'); await page.keyboard.press('Tab')
await page.keyboard.type('400'); await page.keyboard.press('Enter')
await clickCell(page, 0, 1, 1, '[role=dialog]')
await page.keyboard.type('Mason'); await page.keyboard.press('Tab')
await page.keyboard.type('day'); await page.keyboard.press('Tab')
await page.keyboard.type('1'); await page.keyboard.press('Tab')
await page.keyboard.type('800'); await page.keyboard.press('Enter')
await sleep(300)
check('the build-up adds up live: cost 1,000 a unit, and we ask 1,188', (await dialog()).includes('1,000') && (await dialog()).includes('1,188'), (await dialog()).slice(-160))
await clickText(page, 'button', 'Save the rate')
await page.waitForFunction(() => !document.querySelector('[role=dialog]'))
await page.waitForFunction(() => document.querySelector('table[aria-label="Estimate items"]')?.textContent.includes('built up from 2'), { timeout: 8000 })
check('the item now says it is built up from 2 lines, and the rate replaced the typed one', (await main()).includes('1,188'))

await fill(page, '#es-oh', '20')
await page.keyboard.press('Tab')
await sleep(900)
check('changing the overhead reprices the estimate (1,000 +20% +8% = 1,296)', (await main()).includes('1,296'), (await main()).slice(0, 240))

await clickText(page, 'button', 'Submit the price')
await page.waitForFunction(() => document.querySelector('main')?.textContent.includes('Submitted'), { timeout: 8000 })
await toastsGone(page)
check('submitting locks it: no more adding or rating', (await page.$('#ei-desc')) === null)

await clickText(page, 'button', 'We won it')
await page.waitForSelector('[role=dialog]')
await clickText(page, '[role=dialog] button', 'We won it')
await page.waitForFunction(() => document.querySelector('main')?.textContent.includes('became WO-'), { timeout: 10000 })
check('winning it draws up the client work order from it', true)

await done()
