import { api, clickText, fill, launch, open, setValue, signIn, sleep, toastsGone, waitForToast } from './lib.mjs'

// HR: attendance, leave and payroll, the owner's side.
const { page, check, done } = await launch()
await signIn(page)
const stamp = Date.now().toString().slice(-6)
const email = `qa.hr.${stamp}@example.in`
const name = `Meena Payroll${stamp}`
const text = (sel) => page.$eval(sel, (e) => e.textContent.replace(/\s+/g, ' ').trim())
const made = await api(page, 'POST', '/api/employees', { first_name: 'Meena', last_name: `Payroll${stamp}`, email, password: 'Passw0rd-QA1', phone: '', job_title: 'Accountant', department_id: null, reports_to: null, level: 'L1', role: 'employee', permission_role: 'staff', site_ids: [], employment_type: 'full_time', pay_frequency: 'monthly', salary: 30000, tax_rate: 10, start_date: '2026-01-01', emergency_contact: '', emergency_phone: '' })
check('an employee exists to work with', made.status === 200, JSON.stringify(made.data).slice(0, 100))

// She asks for leave, as herself
await api(page, 'POST', '/api/client/logout')
await api(page, 'POST', '/api/employee/auth/login', { email, password: 'Passw0rd-QA1' })
const day = new Date(Date.now() + 30 * 86400000)
while ([0, 6].includes(day.getDay())) day.setDate(day.getDate() + 1)
const iso = `${day.getFullYear()}-${String(day.getMonth() + 1).padStart(2, '0')}-${String(day.getDate()).padStart(2, '0')}`
const asked = await api(page, 'POST', '/api/employee/leave', { leave_type: 'annual', start_date: iso, end_date: iso, reason: 'Wedding' })
check('she has asked for a day of leave', asked.status === 200, JSON.stringify(asked.data).slice(0, 100))
await api(page, 'POST', '/api/employee/auth/logout')
await signIn(page)

// --- Attendance -------------------------------------------------------------------------------
await open(page, '/people/attendance')
await page.waitForSelector('section[aria-label="Today by site"]')
check('Today shows the figures and everybody on a board', (await text('main')).includes('Present today') && (await text('main')).includes(name))
await clickText(page, '[role=tab]', 'History')
await page.waitForSelector('table[aria-label=Attendance]')
check('History is a table with an export', (await text('main')).includes('Export'))
await clickText(page, '[role=tab]', 'Analytics')
await page.waitForFunction(() => document.querySelector('main')?.textContent.includes('Attendance rate'))
check('Analytics shows the rate and the late arrivals', (await text('main')).includes('Late arrivals'))
await clickText(page, '[role=tab]', 'Settings')
await page.waitForSelector('#as-grace')
await fill(page, '#as-grace', '20')
await clickText(page, 'main button', 'Save settings')
await waitForToast(page, 'Settings saved')
check('the grace period is saved', (await api(page, 'GET', '/api/attendance/settings')).data.grace_minutes === 20)
await fill(page, '#as-grace', '15')
await clickText(page, 'main button', 'Save settings')
await toastsGone(page)
await clickText(page, '[role=tab]', 'Overtime')
await page.waitForSelector('#ot-who')
await page.waitForFunction((id) => !!document.querySelector('#ot-who option[value="' + id + '"]'), { timeout: 8000 }, String(made.data.id))
await setValue(page, '#ot-who', String(made.data.id))
await fill(page, '#ot-hours', '2')
await fill(page, '#ot-reason', 'Month-end close')
await clickText(page, 'main button', 'Announce overtime')
await waitForToast(page, 'vertime')
await page.waitForFunction((n) => document.querySelector('table[aria-label="Overtime log"]')?.textContent.includes(n), {}, name)
check('announced overtime is in the log', true)
await toastsGone(page)

// --- Leave ---------------------------------------------------------------------------------------
await open(page, '/people/leave')
await page.waitForSelector('table[aria-label="Leave requests"] tbody tr')
const leaveRow = () => page.evaluate((n) => [...document.querySelectorAll('table[aria-label="Leave requests"] tbody tr')].find((r) => r.textContent.includes(n))?.textContent.replace(/\s+/g, ' '), name)
check('her request is waiting', (await leaveRow())?.includes('Pending'), await leaveRow())
await page.evaluate((n) => [...document.querySelectorAll('table[aria-label="Leave requests"] tbody tr')].find((r) => r.textContent.includes(n)).querySelector('button').click(), name)
await page.waitForSelector('[role=alertdialog], [role=dialog]')
await clickText(page, '[role=alertdialog] button, [role=dialog] button', 'Approve')
await waitForToast(page, 'approved')
await sleep(500)
check('approving it marks it approved', (await leaveRow())?.includes('Approved'), await leaveRow())
await toastsGone(page)

// --- Payroll -------------------------------------------------------------------------------------
await open(page, '/people/payroll')
await page.waitForSelector('main h1')
await clickText(page, 'main button', 'New payslip')
await page.waitForSelector('#ps-emp')
await page.waitForFunction((id) => !!document.querySelector('#ps-emp option[value="' + id + '"]'), { timeout: 8000 }, String(made.data.id))
await setValue(page, '#ps-emp', String(made.data.id))
await page.waitForFunction(() => document.querySelector('#ps-basic')?.value === '30000', { timeout: 8000 })
check('her salary fills in, and the preview works out tax and net', (await text('dl[aria-label=Preview]')).includes('27,506'), await text('dl[aria-label=Preview]'))
await clickText(page, '[role=dialog] button', 'Create payslip')
await waitForToast(page, 'ayslip')
await page.waitForFunction(() => !document.querySelector('[role=dialog]'))
await sleep(500)
const slipRow = () => page.evaluate((n) => [...document.querySelectorAll('table[aria-label=Payslips] tbody tr')].find((r) => r.textContent.includes(n))?.textContent.replace(/\s+/g, ' '), name)
check('the payslip is listed with her net pay', (await slipRow())?.includes('27,506'), await slipRow())
await toastsGone(page)
await page.evaluate((n) => [...document.querySelectorAll('table[aria-label=Payslips] tbody tr')].find((r) => r.textContent.includes(n)).querySelector('button').click(), name)
await page.waitForFunction(() => document.querySelector('[role=dialog]')?.textContent.includes('Earnings'))
check('opening it shows earnings, deductions and net', (await text('[role=dialog]')).includes('Net pay') && (await text('[role=dialog]')).includes('Gross'))
await clickText(page, '[role=dialog] button', 'Mark as paid')
await waitForToast(page, 'paid')
await page.waitForFunction(() => [...document.querySelectorAll('[role=dialog] button')].some((b) => b.textContent.includes('Reopen')))
check('marking it paid shows Reopen', true)
await clickText(page, '[role=dialog] button', 'Reopen')
await page.waitForFunction(() => [...document.querySelectorAll('[role=dialog] button')].some((b) => b.textContent.includes('Mark as paid')))
await toastsGone(page)
await clickText(page, '[role=dialog] button', 'Delete')
await page.waitForFunction(() => [...document.querySelectorAll('[role=dialog], [role=alertdialog]')].some((d) => d.textContent.includes('Delete it')))
await clickText(page, '[role=dialog] button, [role=alertdialog] button', 'Delete it')
await waitForToast(page, 'deleted')
await page.waitForFunction(() => !document.querySelector('[role=dialog], [role=alertdialog]'))
await sleep(500)
check('deleting it removes it from the list', !(await slipRow()))
await toastsGone(page)

// Payroll for everyone
await clickText(page, 'main button', 'Run payroll')
await page.waitForSelector('#pr-start')
await clickText(page, '[role=dialog] button', 'Run payroll')
await waitForToast(page, 'payslip')
await sleep(800)
check('running payroll creates payslips for the people on the books', !!(await slipRow()), await slipRow())
await done()
