import { api, approvedOrder, clickCell, clickText, fill, launch, open, signIn, sleep, waitForToast } from './lib.mjs'

// Holding part of a measurement back from the Measure window itself: recorded with it, printed under it.
const { page, check, done } = await launch({ allow: [] })
await signIn(page)
const o = await approvedOrder(page, { subject: 'Hold while measuring' })
await open(page, `/subcontractors/measurement-book?order=${o.id}`)
await page.waitForSelector('table[aria-label="Items on the order"] tbody tr')
await page.evaluate(() => document.querySelector('table[aria-label="Items on the order"] tbody tr td:last-child button:last-child').click())
await page.waitForSelector('[role=dialog] [role=grid]')
await clickCell(page, 0, 0, 0, '[role=dialog]')
await page.keyboard.type('Wall')
await page.keyboard.press('Tab')
await page.keyboard.type('2')
await page.keyboard.press('Tab')
await page.keyboard.press('Tab')
await page.keyboard.type('10')
await page.keyboard.press('Tab')
await page.keyboard.type('5')
await page.keyboard.press('Enter')
await sleep(300)
const dlg = () => page.$eval('[role=dialog]', (e) => e.textContent.replace(/\s+/g, ' '))
check('the window offers to hold part of it back', (await page.$('input[aria-label="Hold part of this back"]')) !== null)
await page.click('input[aria-label="Hold part of this back"]')
await fill(page, '#m-hold-pct', '10')
await sleep(300)
check('it works out what 10% holds (10 of 100) and what is left to pay', /Held 10\b.*to be paid 90/.test(await page.$eval('[aria-label="Held from this entry"]', (e) => e.textContent.replace(/\s+/g, ' '))), await dlg())
await fill(page, '#m-where', 'Block D')
await clickText(page, '[role=dialog] button', 'Record it in the book')
await page.waitForFunction(() => !document.querySelector('[role=dialog]'), { timeout: 15000 })
await sleep(600)
const book = (await api(page, 'GET', `/api/sub-mb/${o.id}`)).data
const l = book.lines.find((x) => x.item_id === o.items[0].item_id)
check('the book holds 100 measured, 10 held, 90 to bill', l.measured_to_date === 100 && l.held === 10 && l.unbilled === 90, JSON.stringify([l.measured_to_date, l.held, l.unbilled]))
const entry = book.entries.find((e) => !e.kind)
const hold = book.entries.find((e) => e.kind === 'hold')
check('the hold is tied to that entry and carries the reason', hold && hold.group_ref && hold.group_ref === entry.group_ref && /finishes/.test(hold.remarks), JSON.stringify(hold))
await done()
