import { clickText, fill, launch, open, setValue, signIn, sleep, toastsGone, waitForToast } from './lib.mjs'

// Safety: report an incident and close it with its cause and fix; record a toolbox talk; issue a permit and close it.
const { page, check, done } = await launch()
await signIn(page)
const stamp = Date.now().toString().slice(-6)
const text = (sel) => page.$eval(sel, (e) => e.textContent.replace(/\s+/g, ' ').trim())
const gone = () => page.waitForFunction(() => !document.querySelector('[role=dialog]'), { timeout: 10000 })

await open(page, '/projects/safety')
await page.waitForFunction(() => document.querySelector('#sf-job option[value]'), { timeout: 10000 })
await setValue(page, '#sf-job', await page.$eval('#sf-job option[value]:not([value=""])', (o) => o.value))
await sleep(600)
check('the page shows the figures', (await text('main')).includes('Days without a lost-time injury'))

await clickText(page, 'main button', 'New')
await page.waitForSelector('#si-what')
await setValue(page, '#si-kind', 'Near miss')
await fill(page, '#si-where', `Gate 2 ${stamp}`)
await fill(page, '#si-what', `Crane swung a load over the walkway ${stamp}`)
await fill(page, '#si-action', 'Walkway closed for the lift')
await clickText(page, '[role=dialog] button', 'Report it')
await waitForToast(page, 'reported')
await gone()
await sleep(500)
const row = () => page.evaluate((s) => [...document.querySelectorAll('table[aria-label=Incidents] tbody tr')].find((r) => r.textContent.includes(s))?.textContent.replace(/\s+/g, ' '), stamp)
check('the incident is listed, open', /Open/.test(await row()) && /Near miss/.test(await row()), await row())
await toastsGone(page)

await page.evaluate((s) => [...document.querySelectorAll('table[aria-label=Incidents] tbody tr')].find((r) => r.textContent.includes(s)).querySelector('button').click(), stamp)
await page.waitForSelector('#pm-cause')
await fill(page, '#pm-cause', 'No banksman at the gate')
await fill(page, '#pm-fix', 'A banksman for every lift over the walkway')
await clickText(page, '[role=dialog] button', 'Close it')
await waitForToast(page, 'closed')
await gone()
await sleep(500)
check('closing it records the cause and the fix', /Closed/.test(await row()) && /No banksman/.test(await row()), await row())
await toastsGone(page)

await clickText(page, '[role=tab]', 'Toolbox talks')
await clickText(page, 'main button', 'New')
await page.waitForSelector('#pm-topic')
await fill(page, '#pm-topic', `Working at height ${stamp}`)
await fill(page, '#pm-who', '12')
await clickText(page, '[role=dialog] button', 'Record the talk')
await waitForToast(page, 'Talk recorded')
await gone()
await sleep(500)
check('the talk is recorded with its attendance', (await text('table[aria-label="Toolbox talks"] tbody')).includes(`Working at height ${stamp}`))
await toastsGone(page)

await clickText(page, '[role=tab]', 'Permits to work')
await clickText(page, 'main button', 'New')
await page.waitForSelector('#sp-who')
await fill(page, '#sp-where', `Roof ${stamp}`)
await fill(page, '#sp-what', 'Sheeting')
await fill(page, '#sp-who', 'Ramu and gang')
await page.evaluate(() => document.querySelectorAll('[role=dialog] fieldset input[type=checkbox]').forEach((c) => c.click()))
await clickText(page, '[role=dialog] button', 'Issue the permit')
await waitForToast(page, 'issued')
await gone()
await sleep(500)
const prow = () => page.evaluate((s) => [...document.querySelectorAll('table[aria-label=Permits] tbody tr')].find((r) => r.textContent.includes(s))?.textContent.replace(/\s+/g, ' '), stamp)
check('the permit is live', /Live/.test(await prow()), await prow())
await toastsGone(page)
await page.evaluate((s) => [...document.querySelectorAll('table[aria-label=Permits] tbody tr')].find((r) => r.textContent.includes(s)).querySelector('button').click(), stamp)
await page.waitForSelector('#pm-note')
await clickText(page, '[role=dialog] button', 'Close the permit')
await waitForToast(page, 'closed')
await gone()
await sleep(500)
check('closing the permit ends it', /Closed/.test(await prow()), await prow())
await done()
