// The platform console: sign in on its own door, see every company, and its tools open.
import { BASE, launch, sleep } from './lib.mjs'

const { page, check, done } = await launch({ allow: [/401/] })
await page.goto(BASE + '/superadmin-login.html', { waitUntil: 'networkidle0' })
check('the old console address forwards to the React sign-in', page.url().startsWith(BASE + '/next/superadmin/login'), page.url())
await page.type('#login-id', 'hello@billing.com')
await page.type('#login-password', 'TestSuper123')
await page.click('button[type=submit]')
await page.waitForFunction(() => location.pathname === '/next/superadmin', { timeout: 15000 })
await page.waitForSelector('table[aria-label="Clients"] tbody tr', { timeout: 15000 })
const body = () => page.$eval('body', (b) => b.textContent.replace(/\s+/g, ' '))
check('the console lists the companies and shows platform figures', /Total clients/.test(await body()) && /All clients/.test(await body()))
check('it lists what each action costs and the tenant wallets', /What each action costs/.test(await body()) && /Tenant wallets/.test(await body()))
await page.type('input[aria-label="Search clients"]', 'zzzz-nobody')
await page.waitForFunction(() => /No clients yet/.test(document.body.textContent))
check('searching narrows the clients', true)
await page.focus('input[aria-label="Search clients"]')
for (let i = 0; i < 12; i++) await page.keyboard.press('Backspace')
await page.waitForSelector('table[aria-label="Clients"] tbody tr button')
const view = await page.evaluateHandle(() => [...document.querySelectorAll('table[aria-label="Clients"] button')].find((b) => b.textContent === 'View'))
await view.click()
await page.waitForSelector('[role=dialog] dl')
check('a client opens with its details and usage', /Email/.test(await page.$eval('[role=dialog]', (d) => d.textContent)))
await page.keyboard.press('Escape')
await sleep(300)
await page.evaluate(() => [...document.querySelectorAll('button')].find((b) => b.textContent === 'Sign out').click())
await page.waitForFunction(() => location.pathname === '/next/superadmin/login', { timeout: 10000 })
check('signing out returns to the console sign-in', true)
await done()
